# Generated by Django 4.2.17 on 2026-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=None, null=True)),
                ('response', models.TextField(default=None, null=True)),
                ('group', models.TextField(default=None, null=True)),
                ('sender', models.TextField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kharchey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default=None, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.TextField(default=None, null=True)),
                ('sender', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ids', models.TextField(default=None, null=True)),
                ('whatsapp_client_url', models.TextField(default=None, null=True)),
                ('whatsapp_client_url_test', models.TextField(default=None, null=True)),
                ('public_url', models.TextField(default=None, null=True)),
                ('public_url_test', models.TextField(default=None, null=True)),
                ('blacklist_ids', models.TextField(default=None, null=True)),
                ('admin_command_prefix', models.TextField(default=None, null=True)),
                ('classroom_group_id', models.TextField(default=None, null=True)),
                ('classroom_group_id_test', models.TextField(default=None, null=True)),
                ('reminders_api_classroom_id', models.TextField(default=None, null=True)),
                ('reminders_api_classroom_id_test', models.TextField(default=None, null=True)),
                ('reminders_api_classroom_name', models.TextField(default=None, null=True)),
                ('reminders_api_classroom_name_test', models.TextField(default=None, null=True)),
                ('reminders_key', models.TextField(default=None, null=True)),
                ('token_pickle_base64', models.TextField(default=None, null=True)),
                ('ocr_space_api_key', models.TextField(default=None, null=True)),
                ('openai_api_key', models.TextField(default=None, null=True)),
                ('kharchey_group_id', models.TextField(default=None, null=True)),
                ('reminders_api_remind_id', models.TextField(default=None, null=True)),
                ('utils_server_url', models.TextField(default=None, null=True)),
                ('utils_server_password', models.TextField(default=None, null=True)),
                ('last_reminder_id', models.TextField(default=None, null=True)),
                ('last_reminder_time', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(default=None, null=True)),
                ('group_id', models.TextField(default=None, null=True)),
                ('description', models.JSONField(default=None, null=True)),
            ],
        ),
    ]
